// SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

public import SwiftUI

/// The identity of an icon.
///
/// Icons ship as custom SF Symbol assets generated from Material Design Icons,
/// which is what Nextcloud uses everywhere else. Carrying them as symbols rather
/// than as images means they inherit weight, scale, `.foregroundStyle`,
/// hierarchical rendering and optical alignment with adjacent text for free.
///
/// Reach for the catalogue rather than a string:
///
/// ```swift
/// NCIcon(.folderOutline, label: .decorative)
/// ```
public nonisolated struct NCSymbol: Hashable, Sendable {
    /// The name of the generated symbol asset, in Material Design Icons' own
    /// kebab-case spelling.
    public let asset: String

    /// An SF Symbol carrying the same meaning, used until a symbol asset has
    /// been generated for ``asset``.
    ///
    /// `nil` where the system has no equivalent -- brand logos, and the few MDI
    /// glyphs with no counterpart. Those render a visible placeholder rather than
    /// a plausible-but-wrong system glyph.
    public let systemFallback: String?

    public init(asset: String, systemFallback: String? = nil) {
        self.asset = asset
        self.systemFallback = systemFallback
    }

    /// Names for which a generated symbol asset is bundled.
    ///
    /// Regenerated by the icon pipeline alongside the asset catalogue. While it
    /// is empty, every symbol resolves through ``systemFallback``, which is the
    /// correct behaviour before the pipeline has been run -- and it means adding
    /// the assets later is a data change, not a code change.
    public static let bundledAssets: Set<String> = []

    /// Whether this symbol resolves to a bundled MDI asset rather than a
    /// fallback.
    public var hasBundledAsset: Bool { Self.bundledAssets.contains(asset) }
}
